<?php

namespace App\Http\Controllers\V1\Merchendisher\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\V1\Merchendisher\Web\StoreStockInStoreRequest;
use App\Http\Requests\V1\Merchendisher\Web\BulkStoreStockRequest;
use App\Http\Resources\V1\Merchendisher\Web\StockInStoreResource;
use App\Http\Resources\V1\Merchendisher\Web\StockInStorePostResource;
use App\Services\V1\Merchendisher\Web\StockInStoreService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\JsonResponse;
use App\Models\CompanyCustomer;
use App\Helpers\ResponseHelper;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\StocksImport;
/**
 * @OA\Tag(
 *     name="StockInStore",
 *     description="StockInStore management operations"
 * )
 */
class StockInStoreController extends Controller
{
    
    protected $service;

    public function __construct(StockInStoreService $service)
    {
        $this->service = $service;
    }

/**
 * @OA\Get(
 *     path="/api/merchendisher/stockinstore/dropdownlistcustomers",
 *     summary="Get dropdown list of customers for authenticated user",
 *     tags={"StockInStore"},
 *     security={{"bearerAuth":{}}},
 *     @OA\Response(
 *         response=200,
 *         description="Customer listed successfully",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(
 *                 property="message",
 *                 type="string",
 *                 example="Customer listed successfully"
 *             ),
 *             @OA\Property(
 *                 property="code",
 *                 type="integer",
 *                 example=200
 *             ),
 *             @OA\Property(
 *                 property="data",
 *                 type="object",
 *                 description="List of customers",
 *                 example={
 *                     "1": "CT001 - Adarsh",
 *                     "2": "CT002 - John Doe"
 *                 },
 *                 additionalProperties={"type": "string"}
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Unauthenticated"
 *     )
 * )
 */
  public function getDropdownList()
    {
        $userId = Auth::id();

        if (!$userId) {
            return response()->json([], 200); 
        }

        $customers = CompanyCustomer::select(
                'id',
                \DB::raw("CONCAT(customer_code, ' - ', owner_name) as display_name")
            )
            ->where('created_user', $userId)
            ->orderBy('customer_code')
            ->get()
            ->pluck('display_name', 'id'); // [id => "CT001 - Adarsh"]

            return response()->json([
            'message' => 'Customer listed successfully',
            'code' => 200,
            'data' => ($customers),
        ]);
    }
/**
 * @OA\Post(
 *    path="/api/merchendisher/stockinstore/create",
 *    tags={"StockInStore"},
 *    summary="Create a new StockInStore record",
 *    description="Creates a new stock record with assigned customers and inventory details.",
 *    security={{"bearerAuth":{}}},
 *    @OA\RequestBody(
 *        required=true,
 *        @OA\JsonContent(
 *            type="object",
 *            required={"activity_name", "date_from", "date_to", "assign_customers", "assign_inventory"},
 *            @OA\Property(property="code", type="string", example="stk001", description="Optional manual code, autogenerated if not given"),
 *            @OA\Property(property="activity_name", type="string", example="Opening Stock"),
 *            @OA\Property(property="date_from", type="string", format="date", example="2025-10-09"),
 *            @OA\Property(property="date_to", type="string", format="date", example="2025-10-15"),
 *            @OA\Property(
 *                property="assign_customers",
 *                type="array",
 *                @OA\Items(type="integer"),
 *                example={72,86},
 *                description="Array of customer IDs"
 *            ),
 *            @OA\Property(
 *                property="assign_inventory",
 *                type="array",
 *                description="Array of inventory items",
 *                @OA\Items(
 *                    type="object",
 *                    required={"item_id", "item_uom", "capacity"},
 *                    @OA\Property(property="item_id", type="integer", example=17),
 *                    @OA\Property(property="item_uom", type="string", example="1"),
 *                    @OA\Property(property="capacity", type="integer", example=50)
 *                )
 *            )
 *        )
 *    ),
 *    @OA\Response(
 *        response=201,
 *        description="StockInStore created successfully",
 *        @OA\JsonContent(
 *            type="object",
 *            @OA\Property(property="id", type="integer", example=12),
 *            @OA\Property(property="code", type="string", example="STK011"),
 *            @OA\Property(property="uuid", type="string", example="00498dbd-c5fd-4cf7-b298-7c3cecdc9636"),
 *            @OA\Property(property="activity_name", type="string", example="Opening Stock"),
 *            @OA\Property(
 *                property="date_range",
 *                type="object",
 *                @OA\Property(property="from", type="string", format="date", example="2025-10-09"),
 *                @OA\Property(property="to", type="string", format="date", example="2025-10-15")
 *            ),
 *            @OA\Property(
 *                property="assign_customers",
 *                type="array",
 *                @OA\Items(
 *                    type="object",
 *                    @OA\Property(property="id", type="integer", example=72),
 *                    @OA\Property(property="name", type="string", example="Customer A"),
 *                    @OA\Property(property="code", type="string", example="CUST072")
 *                )
 *            ),
 *            @OA\Property(
 *                property="inventories",
 *                type="array",
 *                @OA\Items(
 *                    type="object",
 *                    @OA\Property(property="item_id", type="integer", example=17),
 *                    @OA\Property(property="item_uom", type="string", example="1"),
 *                    @OA\Property(property="capacity", type="integer", example=50)
 *                )
 *            )
 *        )
 *    ),
 *    @OA\Response(
 *        response=422,
 *        description="Validation error",
 *        @OA\JsonContent(
 *            type="object",
 *            @OA\Property(property="success", type="boolean", example=false),
 *            @OA\Property(property="message", type="string", example="The given data was invalid."),
 *            @OA\Property(
 *                property="errors",
 *                type="object",
 *                additionalProperties=@OA\Property(type="array", @OA\Items(type="string"))
 *            )
 *        )
 *    ),
 *    @OA\Response(
 *        response=401,
 *        description="Unauthenticated",
 *        @OA\JsonContent(
 *            @OA\Property(property="success", type="boolean", example=false),
 *            @OA\Property(property="message", type="string", example="Unauthenticated.")
 *        )
 *    )
 * )
 */
 
   public function store(StoreStockInStoreRequest $request): JsonResponse
    {
        $stock = $this->service->create($request->validated());
        $stock->load('inventories');
        return response()->json(new StockInStoreResource($stock), 201);
    }
 /**
 * @OA\Get(
 *     path="/api/merchendisher/stockinstore/list",  
 *     tags={"StockInStore"},
 *     summary="Get all StockInStore records",
 *     description="Fetches a list of all StockInStore records with pagination and optional search.",
 *     security={{"bearerAuth":{}}},
 * 
 *     @OA\Parameter(
 *         name="search",
 *         in="query",
 *         required=false,
 *         description="Search keyword to filter stock records by various fields",
 *         @OA\Schema(type="string", example="Inventory")
 *     ),
 *     @OA\Parameter(
 *         name="per_page",
 *         in="query",
 *         required=false,
 *         description="Number of records per page",
 *         @OA\Schema(type="integer", example=10)
 *     ),
 * 
 *     @OA\Response(
 *         response=200,
 *         description="Stocks fetched successfully",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="success", type="boolean", example=true),
 *             @OA\Property(property="message", type="string", example="Stocks fetched successfully"),
 *             @OA\Property(
 *                 property="data",
 *                 type="array",
 *                 @OA\Items(
 *                     type="object",
 *                     @OA\Property(property="id", type="integer", example=123),
 *                     @OA\Property(property="code", type="string", example="stk001"),
 *                     @OA\Property(property="uuid", type="string", example="550e8400-e29b-41d4-a716-446655440000"),
 *                     @OA\Property(property="activity_name", type="string", example="Inventory Check"),
 *                     @OA\Property(property="date_from", type="string", format="date", example="2025-10-01"),
 *                     @OA\Property(property="date_to", type="string", format="date", example="2025-10-05"),
 *                     @OA\Property(
 *                         property="assign_customers",
 *                         type="array",
 *                         @OA\Items(type="integer", example=1),
 *                         description="List of customer IDs assigned to this stock"
 *                     ),
 *                     @OA\Property(property="created_user", type="string", example="1"),
 *                     @OA\Property(property="updated_user", type="string", example="2"),
 *                     @OA\Property(property="deleted_user", type="string", example="3"),

 *                     @OA\Property(
 *                         property="createdUser",
 *                         type="object",
 *                         @OA\Property(property="firstname", type="string", example="Alice"),
 *                         @OA\Property(property="lastname", type="string", example="Smith"),
 *                         @OA\Property(property="username", type="string", example="alice123")
 *                     ),
 *                     @OA\Property(
 *                         property="updatedUser",
 *                         type="object",
 *                         @OA\Property(property="firstname", type="string", example="Bob"),
 *                         @OA\Property(property="lastname", type="string", example="Jones"),
 *                         @OA\Property(property="username", type="string", example="bobby")
 *                     ),
 *                     @OA\Property(
 *                         property="deletedUser",
 *                         type="object",
 *                         @OA\Property(property="firstname", type="string", example="Carol"),
 *                         @OA\Property(property="lastname", type="string", example="Doe"),
 *                         @OA\Property(property="username", type="string", example="carol_d")
 *                     ),
 *                     @OA\Property(property="created_at", type="string", format="date-time", example="2025-10-01T12:00:00Z"),
 *                     @OA\Property(property="updated_at", type="string", format="date-time", example="2025-10-02T12:00:00Z"),
 *                     @OA\Property(property="deleted_at", type="string", format="date-time", example="2025-10-03T12:00:00Z")
 *                 ),
 *                 description="List of StockInStore records"
 *             ),
 *             @OA\Property(
 *                 property="pagination",
 *                 type="object",
 *                 @OA\Property(property="total", type="integer", example=100),
 *                 @OA\Property(property="per_page", type="integer", example=10),
 *                 @OA\Property(property="current_page", type="integer", example=1),
 *                 @OA\Property(property="last_page", type="integer", example=10),
 *                 @OA\Property(property="next_page_url", type="string", example="https://api.example.com/stocks?page=2"),
 *                 @OA\Property(property="prev_page_url", type="string", example="https://api.example.com/stocks?page=1")
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Unauthenticated",
 *         @OA\JsonContent(
 *             @OA\Property(property="success", type="boolean", example=false),
 *             @OA\Property(property="message", type="string", example="Unauthenticated.")
 *         )
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Internal server error",
 *         @OA\JsonContent(
 *             @OA\Property(property="success", type="boolean", example=false),
 *             @OA\Property(property="message", type="string", example="An unexpected error occurred.")
 *         )
 *     )
 * )
 */
        public function index()
    {
        $stocks = $this->service->getAll();
        $stocks->load('inventories');
        return ResponseHelper::paginatedResponse(
        'Stocks fetched successfully',
        StockInStoreResource::class,
        $stocks
      );
    }

/**
 * @OA\Get(
 *     path="/api/merchendisher/stockinstore/show/{uuid}",
 *     tags={"StockInStore"},
 *     summary="Get a specific StockInStore record by UUID",
 *     description="Fetches a specific StockInStore record using the provided UUID.",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(
 *         name="uuid",
 *         in="path",
 *         description="The UUID of the StockInStore record to retrieve",
 *         required=true,
 *         @OA\Schema(type="string", example="123e4567-e89b-12d3-a456-426614174000")
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="Stock retrieved successfully",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="message", type="string", example="Stock retrieved successfully"),
 *             @OA\Property(property="code", type="integer", example=200),
 *             @OA\Property(
 *                 property="data",
 *                 type="object",
 *                 @OA\Property(property="id", type="integer", example=1),
 *                 @OA\Property(property="code", type="string", example="STOCK1234"),
 *                 @OA\Property(property="uuid", type="string", example="123e4567-e89b-12d3-a456-426614174000"),
 *                 @OA\Property(property="activity_name", type="string", example="Stock Check"),
 *                 @OA\Property(property="date_from", type="string", format="date", example="2025-01-01"),
 *                 @OA\Property(property="date_to", type="string", format="date", example="2025-01-31"),
 *                 @OA\Property(property="assign_customers", type="string", example="Customer A, Customer B"),
 *                 @OA\Property(property="created_user", type="string", example="admin"),
 *                 @OA\Property(property="updated_user", type="string", example="admin"),
 *                 @OA\Property(property="deleted_user", type="string", example="admin"),
 *                 @OA\Property(property="created_at", type="string", format="date-time", example="2025-01-01T10:00:00Z"),
 *                 @OA\Property(property="updated_at", type="string", format="date-time", example="2025-01-15T10:00:00Z"),
 *                 @OA\Property(property="deleted_at", type="string", format="date-time", example="2025-02-01T10:00:00Z")
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=404,
 *         description="Stock not found",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="Stock not found."),
 *             @OA\Property(property="code", type="integer", example=404)
 *         )
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Unauthenticated",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="Unauthenticated."),
 *             @OA\Property(property="code", type="integer", example=401)
 *         )
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Internal server error",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="An unexpected error occurred."),
 *             @OA\Property(property="code", type="integer", example=500)
 *         )
 *     )
 * )
 */
 
      public function show($uuid)
{
    $stock = $this->service->getByUuid($uuid);
    $stock->load('inventories');
    return response()->json([
        'message' => 'Stock retrieved successfully',
        'code' => 200,
        'data' => new StockInStoreResource($stock),
    ]);
}
/**
 * @OA\Put(
 *     path="/api/merchendisher/stockinstore/update/{uuid}",
 *     tags={"StockInStore"},
 *     summary="Update a specific StockInStore record by UUID",
 *     description="Updates a specific StockInStore record using the provided UUID.",
 *     security={{"bearerAuth":{}}},
 *     @OA\Parameter(
 *         name="uuid",
 *         in="path",
 *         description="The UUID of the StockInStore record to update",
 *         required=true,
 *         @OA\Schema(type="string", example="123e4567-e89b-12d3-a456-426614174000")
 *     ),
 *     @OA\RequestBody(
 *         required=true,
 *         description="StockInStore update data",
 *         @OA\JsonContent(
 *             type="object",
 *             required={"activity_name", "date_from", "date_to","assign_customers"},
 *             @OA\Property(property="code", type="string", example="STOCK1234"),
 *             @OA\Property(property="activity_name", type="string", example="Stock Check"),
 *             @OA\Property(property="date_from", type="string", format="date", example="2025-01-01"),
 *             @OA\Property(property="date_to", type="string", format="date", example="2025-01-31"),
 *             @OA\Property(
 *                     property="assign_customers",
 *                     type="array",
 *                     @OA\Items(type="integer"),
 *                     example={1,2,3}
 *                 )
 *         )
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="Stock updated successfully",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="message", type="string", example="Stock Updated successfully"),
 *             @OA\Property(property="code", type="integer", example=200),
 *             @OA\Property(
 *                 property="data",
 *                 type="object",
 *                 @OA\Property(property="id", type="integer", example=1),
 *                 @OA\Property(property="code", type="string", example="STOCK1234"),
 *                 @OA\Property(property="uuid", type="string", example="123e4567-e89b-12d3-a456-426614174000"),
 *                 @OA\Property(property="activity_name", type="string", example="Stock Check"),
 *                 @OA\Property(property="date_from", type="string", format="date", example="2025-01-01"),
 *                 @OA\Property(property="date_to", type="string", format="date", example="2025-01-31"),
 *                 @OA\Property(property="assign_customers", type="string", example="Customer A, Customer B"),
 *                 @OA\Property(property="created_user", type="string", example="admin"),
 *                 @OA\Property(property="updated_user", type="string", example="admin"),
 *                 @OA\Property(property="deleted_user", type="string", example="admin"),
 *                 @OA\Property(property="created_at", type="string", format="date-time", example="2025-01-01T10:00:00Z"),
 *                 @OA\Property(property="updated_at", type="string", format="date-time", example="2025-01-15T10:00:00Z"),
 *                 @OA\Property(property="deleted_at", type="string", format="date-time", example="2025-02-01T10:00:00Z")
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=404,
 *         description="Stock not found",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="Stock not found."),
 *             @OA\Property(property="code", type="integer", example=404)
 *         )
 *     ),
 *     @OA\Response(
 *         response=422,
 *         description="Validation error",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="The code field is required."),
 *             @OA\Property(property="code", type="integer", example=422)
 *         )
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Unauthenticated",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="Unauthenticated."),
 *             @OA\Property(property="code", type="integer", example=401)
 *         )
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Internal server error",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="An unexpected error occurred."),
 *             @OA\Property(property="code", type="integer", example=500)
 *         )
 *     )
 * )
 */
    public function update(StoreStockInStoreRequest $request, $uuid): JsonResponse
    {
        $stock = $this->service->update($uuid, $request->validated());
        $stock->load('inventories');
         return response()->json([
        'message' => 'Stock Updated successfully',
        'code' => 200,
        'data' => new StockInStoreResource($stock),
      ]);
    }
/**
 * @OA\Delete(
 *     path="/api/merchendisher/stockinstore/delete/{uuid}",
 *     summary="Delete a stock",
 *     description="Deletes a stock record by its UUID",
 *     tags={"StockInStore"},
 *   security={{"bearerAuth":{}}},
 *     @OA\Parameter(
 *         name="uuid",
 *         in="path",
 *         description="The UUID of the stock to delete",
 *         required=true,
 *         @OA\Schema(
 *             type="string",
 *             format="uuid"
 *         )
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="Stock deleted successfully",
 *         @OA\JsonContent(
 *             @OA\Property(
 *                 property="message",
 *                 type="string",
 *                 example="Stock deleted successfully"
 *             ),
 *             @OA\Property(
 *                 property="code",
 *                 type="integer",
 *                 example=200
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=404,
 *         description="Stock not found",
 *         @OA\JsonContent(
 *             @OA\Property(
 *                 property="message",
 *                 type="string",
 *                 example="Stock not found"
 *             ),
 *             @OA\Property(
 *                 property="code",
 *                 type="integer",
 *                 example=404
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Internal server error",
 *         @OA\JsonContent(
 *             @OA\Property(
 *                 property="message",
 *                 type="string",
 *                 example="Something went wrong"
 *             ),
 *             @OA\Property(
 *                 property="code",
 *                 type="integer",
 *                 example=500
 *             )
 *         )
 *     )
 * )
 */
    public function destroy($uuid): JsonResponse
    {
        $this->service->delete($uuid);
        return response()->json([
        'message' => 'Stock deleted successfully',
        'code' => 200,
     ]);
    }

/**
 * @OA\Post(
 *     path="/api/merchendisher/stockinstore/bluckupload",
 *     tags={"StockInStore"},
 *     summary="Bulk upload stock from CSV or XLS file",
 *     description="Uploads multiple stock records from a CSV or XLS file.",
 *     security={{"bearerAuth":{}}},
 *     @OA\RequestBody(
 *         required=true,
 *         @OA\MediaType(
 *             mediaType="multipart/form-data",
 *             @OA\Schema(
 *                 required={"file"},
 *                 @OA\Property(
 *                     description="Upload CSV or XLS file",
 *                     property="file",
 *                     type="string",
 *                     format="binary"
 *                 )
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=201,
 *         description="Bulk upload successful"
 *     ),
 *     @OA\Response(
 *         response=422,
 *         description="Validation error"
 *     )
 * )
 */
public function bulkUpload(BulkStoreStockRequest $request): JsonResponse
    {
        $stocks = $this->service->bulkUpload($request->file('file'));

        return response()->json([
            'message' => 'Bulk upload successful',
            'data'    => StockInStoreResource::collection(collect($stocks)),
        ], 201);
    }
/**
 * @OA\Get(
 *     path="/api/merchendisher/stockinstore/posts/{uuid}",
 *     tags={"StockInStore"},
 *     summary="Get stock in store posts by stock UUID",
 *     security={{"bearerAuth":{}}},
 *     description="Fetch paginated stock in store posts using stock UUID",
 *
 *     @OA\Parameter(
 *         name="uuid",
 *         in="path",
 *         required=true,
 *         description="Stock In Store UUID",
 *         @OA\Schema(type="string", example="5b9c9f2d-98a2-4f14-b7ad-9c12abcd1234")
 *     ),
 *
 *     @OA\Parameter(
 *         name="page",
 *         in="query",
 *         required=false,
 *         description="Pagination page number",
 *         @OA\Schema(type="integer", example=1)
 *     ),
 *
 *     @OA\Response(
 *         response=200,
 *         description="Stocks Posts fetched successfully",
 *         @OA\JsonContent(
 *             type="object",
 *             @OA\Property(property="status", type="boolean", example=true),
 *             @OA\Property(property="message", type="string", example="Stocks Posts fetched successfully"),
 *             @OA\Property(
 *                 property="data",
 *                 type="array",
 *                 @OA\Items(type="object")
 *             ),
 *             @OA\Property(
 *                 property="meta",
 *                 type="object",
 *                 @OA\Property(property="current_page", type="integer", example=1),
 *                 @OA\Property(property="last_page", type="integer", example=3),
 *                 @OA\Property(property="per_page", type="integer", example=10),
 *                 @OA\Property(property="total", type="integer", example=25)
 *             )
 *         )
 *     ),
 *
 *     @OA\Response(
 *         response=404,
 *         description="Stock not found"
 *     )
 * )
 */
public function postsByStockUuid(string $uuid)
    {
        $posts = $this->service->getPostsByStockUuid($uuid);
        return ResponseHelper::paginatedResponse(
        'Stocks Posts fetched successfully',
        StockInStorePostResource::class,
        $posts
      );
    }
}