<?php

namespace App\Http\Controllers\V1\Settings\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\V1\Settings\Web\ServiceTypeRequest;
use App\Http\Resources\V1\Settings\Web\ServiceTypeResource;
use App\Services\V1\Settings\Web\ServiceTypeService;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use App\Traits\ApiResponse;
use Illuminate\Http\Request;

/**
 * @OA\Tag(
 *     name="ServiceTypes",
 *     description="Service type management"
 * )
 */
class ServiceTypeController extends Controller
{
    use ApiResponse;
    protected ServiceTypeService $service;

    public function __construct(ServiceTypeService $service)
    {
        $this->service = $service;
    }

    /**
     * @OA\Get(
     *     path="/api/settings/service-types/list",
     *     tags={"ServiceTypes"},
     *     security={{"bearerAuth":{}}},
     *     summary="List service types with pagination & filters",
     *     @OA\Parameter(name="code", in="query", @OA\Schema(type="string")),
     *     @OA\Response(response=200, description="Paginated list of service types")
     * )
     */
    public function index(Request $request)
    {
        $perPage = $request->get('per_page', 10);
        $filters = $request->only(['status', 'code', 'name']);

        $data = $this->service->all($perPage, $filters);

        return response()->json([
            'status' => 'success',
            'code' => 200,
            'message' => 'Service types fetched successfully',
            'data' => ServiceTypeResource::collection($data->items()),
            'pagination' => [
                'page' => $data->currentPage(),
                'limit' => $data->perPage(),
                'totalPages' => $data->lastPage(),
                'totalRecords' => $data->total(),
            ]
        ]);
    }

    /**
     * @OA\Get(
     *     path="/api/settings/service-types/generate-code",
     *     tags={"ServiceTypes"},
     *     security={{"bearerAuth":{}}},
     *     summary="Generate unique ServiceType code",
     *     description="Returns a unique auto-generated ServiceType code which can be shown as readonly in UI",
     *     @OA\Response(
     *         response=200,
     *         description="Unique ServiceType code generated",
     *         @OA\JsonContent(
     *             @OA\Property(property="status", type="string", example="success"),
     *             @OA\Property(property="code", type="integer", example=200),
     *             @OA\Property(property="message", type="string", example="Unique ServiceType code generated successfully"),
     *             @OA\Property(property="data", type="object",
     *                 @OA\Property(property="code", type="string", example="ST001")
     *             )
     *         )
     *     )
     * )
     */
    public function generateCode()
    {
        try {
            $code = $this->service->generateCode();

            return $this->success(
                data: ['code' => $code],
                message: 'Unique ServiceType code generated successfully'
            );
        } catch (\Exception $e) {
            return $this->fail($e->getMessage(), 500);
        }
    }

    /**
     * @OA\Post(
     *     path="/api/settings/service-types/add",
     *     tags={"ServiceTypes"},
     *     security={{"bearerAuth":{}}},
     *     summary="Create a new ServiceType",
     *     description="Create a new ServiceType. Code will be auto-generated by backend.",
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\JsonContent(
     *             required={"name","status"},
     *             @OA\Property(property="name", type="string", example="Logistics Service"),
     *             @OA\Property(property="status", type="integer", enum={0,1}, example=1)
     *         )
     *     ),
     *     @OA\Response(
     *         response=201,
     *         description="ServiceType created successfully",
     *         @OA\JsonContent(
     *             @OA\Property(property="status", type="string", example="success"),
     *             @OA\Property(property="code", type="integer", example=201),
     *             @OA\Property(property="message", type="string", example="ServiceType created successfully"),
     *             @OA\Property(property="data", type="object",
     *                 @OA\Property(property="uuid", type="string", example="6f9c1440-7f52-4f54-8f94-76adf1b1b111"),
     *                 @OA\Property(property="code", type="string", example="ST001"),
     *                 @OA\Property(property="name", type="string", example="Logistics Service"),
     *                 @OA\Property(property="status", type="integer", example=1),
     *                 @OA\Property(property="created_user", type="integer", example=1),
     *                 @OA\Property(property="updated_user", type="integer", example=1),
     *                 @OA\Property(property="created_at", type="string", format="date-time"),
     *                 @OA\Property(property="updated_at", type="string", format="date-time")
     *             )
     *         )
     *     )
     * )
     */
    public function store(ServiceTypeRequest $request)
    {
        $serviceType = $this->service->create($request->validated());

        return response()->json([
            'status' => 'success',
            'code' => 201,
            'message' => 'Service type created successfully',
            'data' => new ServiceTypeResource($serviceType)
        ], 201);
    }

    /**
     * @OA\Get(
     *     path="/api/settings/service-types/export",
     *     tags={"ServiceTypes"},
     *     security={{"bearerAuth":{}}},
     *     summary="Export ServiceTypes to CSV",
     *     @OA\Response(response=200, description="CSV File Download")
     * )
     */
    public function exportCsv(): BinaryFileResponse
    {
        $filePath = $this->service->exportToCsv();
        // dd($filePath);
        return response()->download($filePath)->deleteFileAfterSend(true);
    }


    /**
     * @OA\Get(
     *     path="/api/settings/service-types/show/{uuid}",
     *     tags={"ServiceTypes"},
     *     security={{"bearerAuth":{}}},
     *     summary="Get single service type by UUID",
     *     @OA\Parameter(name="uuid", in="path", required=true, @OA\Schema(type="string")),
     *     @OA\Response(response=200, description="OK"),
     *     @OA\Response(response=404, description="Not Found")
     * )
     */
    public function show(string $uuid)
    {
        $serviceType = $this->service->findByUuid($uuid);

        return response()->json([
            'status' => 'success',
            'code' => 200,
            'message' => 'Service type fetched successfully',
            'data' => new ServiceTypeResource($serviceType)
        ]);
    }

    /**
     * @OA\Put(
     *     path="/api/settings/service-types/update/{uuid}",
     *     tags={"ServiceTypes"},
     *     security={{"bearerAuth":{}}},
     *     summary="Update a service type by UUID",
     *     @OA\Parameter(name="uuid", in="path", required=true, @OA\Schema(type="string")),
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\JsonContent(
     *             @OA\Property(property="name", type="string"),
     *             @OA\Property(property="status", type="integer", enum={0,1})
     *         )
     *     ),
     *     @OA\Response(response=200, description="Updated"),
     *     @OA\Response(response=422, description="Validation error"),
     *     @OA\Response(response=404, description="Not Found")
     * )
     */
    public function update(ServiceTypeRequest $request, string $uuid)
    {
        $serviceType = $this->service->updateByUuid($uuid, $request->validated());

        return response()->json([
            'status' => 'success',
            'code' => 200,
            'message' => 'Service type updated successfully',
            'data' => new ServiceTypeResource($serviceType)
        ]);
    }

    /**
     * @OA\Delete(
     *     path="/api/settings/service-types/delete/{uuid}",
     *     tags={"ServiceTypes"},
     *     security={{"bearerAuth":{}}},
     *     summary="Delete service type by UUID",
     *     @OA\Parameter(name="uuid", in="path", required=true, @OA\Schema(type="string")),
     *     @OA\Response(response=204, description="Deleted")
     * )
     */
    public function destroy(string $uuid)
    {
        try {
            $deleted = $this->service->deleteByUuid($uuid);

            if ($deleted) {
                return $this->success(
                    data: null,
                    message: 'Service Type deleted successfully',
                    code: 200
                );
            }

            return $this->fail(
                message: 'Failed to delete Company Type',
                code: 400
            );
        } catch (\Exception $e) {
            return $this->fail(
                message: $e->getMessage(),
                code: 404
            );
        }
    }

    // /**
    //  * @OA\Post(
    //  *     path="/api/settings/service-types/restore/{uuid}",
    //  *     tags={"ServiceTypes"},
    //  *     security={{"bearerAuth":{}}},
    //  *     summary="Restore soft-deleted service type by UUID",
    //  *     @OA\Parameter(name="uuid", in="path", required=true, @OA\Schema(type="string")),
    //  *     @OA\Response(response=200, description="Restored")
    //  * )
    //  */
    // public function restore(string $uuid)
    // {
    //     $serviceType = $this->service->restore($uuid);

    //     return response()->json([
    //         'status' => 'success',
    //         'code' => 200,
    //         'message' => 'Service type restored successfully',
    //         'data' => new ServiceTypeResource($serviceType)
    //     ]);
    // }
}
